// next/components/development/AuthLoadingTest.tsx
'use client';

import { useAuth } from '@/hooks/useAuth';
import LoadingBlock from '@/components/ui/LoadingBlock';

export default function AuthLoadingTest({
  text,
  auth,
}: {
  text: string;
  auth: ReturnType<typeof useAuth>;
}) {
  return (
    <div>
      <div>
        <div>
          <div>text: {text}</div>
          <div>auth.loading: {auth.loading ? 'on' : 'off'}</div>
          <div>auth.user: {auth.user ? auth.user.name : 'none'}</div>
        </div>
      </div>

      <div className="mt-5">
        {auth.loading ? (
          <LoadingBlock />
        ) : (
          <div>
            <div>text: {text}</div>
            <div>auth.loading: {auth.loading ? 'on' : 'off'}</div>
            <div>auth.user: {auth.user ? auth.user.name : 'none'}</div>
          </div>
        )}
      </div>
    </div>
  );
}

// nuxt/app/components/development/AuthLoadingTest.vue
<template>
  <div>
    <div>
      <div>
        <div>text: {{ text }}</div>
        <div>auth.loading: {{ auth.loading.value ? 'on' : 'off' }}</div>
        <div>auth.user: {{ auth.user.value ? auth.user.value.name : 'none' }}</div>
      </div>
    </div>

    <div class="mt-5">
      <LoadingBlock v-if="auth.loading.value" />
      <div v-else>
        <div>text: {{ text }}</div>
        <div>auth.loading: {{ auth.loading.value ? 'on' : 'off' }}</div>
        <div>auth.user: {{ auth.user.value ? auth.user.value.name : 'none' }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuth } from '@/composables/useAuth'
import LoadingBlock from '@/components/ui/LoadingBlock.vue'

interface Props {
  text: string
  auth: ReturnType<typeof useAuth>
}

// props 定義
const props = defineProps<Props>()
</script>
