// next/components/development/SendTest.tsx
'use client';
import React, { useState } from 'react';
import { sendRest } from '@/services/api/rest';

export default function SendTest() {
  const [message, setMessage] = useState('');
  const [result, setResult] = useState('');

  const handleSubmit = async (
    e: React.SyntheticEvent<HTMLFormElement, SubmitEvent>,
  ) => {
    e.preventDefault();

    const data = {
      message,
    };
    const url = '/send-test';

    const res = await sendRest<{ message: string }>(url, data);

    console.log('res', res);

    setResult(res.message);
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-2">
      <textarea
        placeholder="メッセージ"
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        className="app-form-input"
      />
      <button type="submit" className="app-btn-primary">
        送信
      </button>
      {result && <p>{result}</p>}
    </form>
  );
}

// nuxt/app/components/development/SendTest.vue
<template>
  <form @submit.prevent="handleSubmit" class="flex flex-col gap-2">
    <textarea
      placeholder="メッセージ"
      v-model="message"
      class="app-form-input"
    />
    <button type="submit" class="app-btn-primary">
      送信
    </button>
    <p v-if="result">{{ result }}</p>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { sendRest } from '@/services/api/rest'

const message = ref('')
const result = ref('')

const handleSubmit = async () => {
  const data = { message: message.value }
  const url = '/send-test'

  try {
    const res = await sendRest<{ message: string }>(url, data)
    console.log('res', res)
    result.value = res.message
  } catch (e) {
    console.error(e)
    result.value = '送信に失敗しました'
  }
}
</script>
