// next/app/development/page.tsx
'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

import SendTest from '@/components/development/SendTest';
import LoginTest from '@/components/development/LoginTest';
import AuthLoadingTest from '@/components/development/AuthLoadingTest';

import ClientLayout from '@/components/layouts/ClientLayout';
import { useAuth } from '@/hooks/useAuth';
import LoadingBlock from '@/components/ui/LoadingBlock';

export default function Development() {
  console.log('Development');

  const [text, setText] = useState('');

  const auth = useAuth((user) => {
    console.log('callback', user);

    if (user) setText('test ' + user.name);
  });

  const blockClass = 'border-2 p-10 my-5';

  return (
    <ClientLayout auth={auth}>
      <div>
        <h2 className="app-h2">Development</h2>

        {auth.loading ? (
          <LoadingBlock height="12rem" />
        ) : (
          <div className={blockClass}>
            <SendTest />
          </div>
        )}

        <div className={blockClass}>
          <LoginTest />
        </div>

        <div className={blockClass}>
          <AuthLoadingTest text={text} auth={auth} />
        </div>

        <div className={blockClass}>
          <Link href="/profile" prefetch={false} className="app-link-normal">
            ユーザーページ
          </Link>
        </div>
      </div>
    </ClientLayout>
  );
}

// nuxt/app/pages/development.vue
<template>
  <ClientLayout :auth="auth">
    <div>
      <h2 class="app-h2">Development</h2>

      <!-- 認証ロード中 -->
      <LoadingBlock v-if="auth.loading.value" height="12rem" />

      <!-- 認証完了後 -->
      <div v-else class="border-2 p-10 my-5">
        <SendTest />
      </div>

      <div class="border-2 p-10 my-5">
        <LoginTest />
      </div>

      <div class="border-2 p-10 my-5">
        <AuthLoadingTest :text="text" :auth="auth" />
      </div>

      <div class="border-2 p-10 my-5">
        <NuxtLink to="/profile" class="app-link-normal">
          ユーザーページ
        </NuxtLink>
      </div>
    </div>
  </ClientLayout>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import ClientLayout from '@/components/layouts/ClientLayout.vue'
import LoadingBlock from '@/components/ui/LoadingBlock.vue'
import SendTest from '@/components/development/SendTest.vue'
import LoginTest from '@/components/development/LoginTest.vue'
import AuthLoadingTest from '@/components/development/AuthLoadingTest.vue'
import { useAuth } from '@/composables/useAuth'

// 認証
const auth = useAuth()

// 認証後に text を設定
const text = ref('')
watch(
  () => auth.user,
  (user) => {
    if (user) {
      text.value = 'test ' + user.value?.name
    }
  }
)
</script>
